### ISSUE TITLE
1

### ISSUE THREAD

**Issue by hohhoo** [caihongwang/Love#1]

**Comment by caihongwang** [comment]
知道这里是github,  这份代码是我收藏的，在此项目里面上传串自己的收款码，当时是用来测试GitHub当做免费的图片CND服务器，如果你觉得我更改了你的开源代码，请将你自己的代码增加private；我将你的代码传播到Github并没有传播，而是方便自己获取，你要是很在意自己的这份代码，private是很好的选项.
